# Child Mortality Estimates

In [1]:
import pandas as pd
import numpy as np

/usr/local/lib/python3.5/site-packages/matplotlib/__init__.py:872: UserWarning: axes.color_cycle is deprecated and replaced with axes.prop_cycle; please use the latter.
  warnings.warn(self.msg_depr % (key, alt_key))

In [29]:
import re

def to_concept_id(s):
    '''convert a string to lowercase alphanumeric + underscore id for concepts'''
    s1 = re.sub(r'[/ -\.\*]+', '_', s).lower()
    
    if s1[-1] == '_':
        s1 = s1[:-1]
    
    return s1.strip()

In [5]:
data = pd.read_excel('./source/RatesDeaths_AllIndicators.xlsx', skiprows=6)

In [6]:
data.head()

,ISO Code,CountryName,Uncertainty bounds*,U5MR.1950,U5MR.1951,U5MR.1952,U5MR.1953,U5MR.1954,U5MR.1955,U5MR.1956,...,Neonatal.Deaths.2006,Neonatal.Deaths.2007,Neonatal.Deaths.2008,Neonatal.Deaths.2009,Neonatal.Deaths.2010,Neonatal.Deaths.2011,Neonatal.Deaths.2012,Neonatal.Deaths.2013,Neonatal.Deaths.2014,Neonatal.Deaths.2015
0,AFG,Afghanistan,Lower,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,23880,23638,23216,22689,22179,21266,20273,19440,18629,17573
1,AFG,Afghanistan,Median,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,44007,43856,43469,42791,42311,41052,39588,38263,37038,36242
2,AFG,Afghanistan,Upper,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,65784,65663,65435,64608,63632,62498,61129,60190,58975,58900
3,AGO,Angola,Lower,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,25458,25686,25732,25618,25578,25238,24632,23930,23544,23394
4,AGO,Angola,Median,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,49499,50458,50990,51640,52107,52434,52604,52860,53041,53164

In [8]:
c = data.columns[3:]

In [11]:
res = []

for i in c:
    s = i[:-5]
    if not s in res:
        res.append(s)

In [12]:
res

['U5MR', 'IMR', 'NMR', 'Under.five.Deaths', 'Infant.Deaths', 'Neonatal.Deaths']

In [30]:
concepts = []
concepts_name = []

for i in res:
    ns = [i + '.Lower', i+'.Median', i+'.Upper']
    concepts.append(to_concept_id(ns[0]))
    concepts.append(to_concept_id(ns[1]))
    concepts.append(to_concept_id(ns[2]))
    
    concepts_name.append(ns[0])
    concepts_name.append(ns[1])
    concepts_name.append(ns[2])

In [31]:
concepts

['u5mr_lower',
 'u5mr_median',
 'u5mr_upper',
 'imr_lower',
 'imr_median',
 'imr_upper',
 'nmr_lower',
 'nmr_median',
 'nmr_upper',
 'under_five_deaths_lower',
 'under_five_deaths_median',
 'under_five_deaths_upper',
 'infant_deaths_lower',
 'infant_deaths_median',
 'infant_deaths_upper',
 'neonatal_deaths_lower',
 'neonatal_deaths_median',
 'neonatal_deaths_upper']

In [18]:
concepts_continuous = pd.DataFrame([], columns=['concept', 'name', 'type'])

In [19]:
concepts_continuous['name'] = concepts_name

In [20]:
concepts_continuous['concept'] = concepts

In [21]:
concepts_continuous['type'] = 'measure'

In [22]:
concepts_continuous

                     concept                      name     type
0                 u5mr_lower                U5MR.Lower  measure
1                u5mr_median               U5MR.Median  measure
2                 u5mr_upper                U5MR.Upper  measure
3                  imr_lower                 IMR.Lower  measure
4                 imr_median                IMR.Median  measure
5                  imr_upper                 IMR.Upper  measure
6                  nmr_lower                 NMR.Lower  measure
7                 nmr_median                NMR.Median  measure
8                  nmr_upper                 NMR.Upper  measure
9    under_five_deaths_lower   Under.five.Deaths.Lower  measure
10  under_five_deaths_median  Under.five.Deaths.Median  measure
11   under_five_deaths_upper   Under.five.Deaths.Upper  measure
12       infant_deaths_lower       Infant.Deaths.Lower  measure
13      infant_deaths_median      Infant.Deaths.Median  measure
14       infant_deaths_upper       Infant.Deaths.Upper  measure
15     neonatal_deaths_lower     Neonatal.Deaths.Lower  measure
16    neonatal_deaths_median    Neonatal.Deaths.Median  measure
17     neonatal_deaths_upper     Neonatal.Deaths.Upper  measure

In [46]:
!mkdir output/

In [49]:
concepts_continuous.to_csv('output/ddf--concepts--continuous.csv', index=False)

In [27]:
concept_dis = data.columns[:3]

In [28]:
concept_dis

Index(['ISO Code', 'CountryName', 'Uncertainty bounds*'], dtype='object')

In [32]:
concept_dis_df = pd.DataFrame([], columns=['concept', 'name', 'type'])

In [34]:
concept_dis_df['name'] = concept_dis

In [35]:
concept_dis_df['concept'] = concept_dis_df['name'].apply(to_concept_id)

In [38]:
concept_dis_df['type'] = "string"

In [41]:
concept_dis_df = concept_dis_df.append(pd.DataFrame([['country', 'Country', 'entity_domain']], index=[0], columns=concept_dis_df.columns))

In [43]:
concept_dis_df = concept_dis_df.append(pd.DataFrame([['year', 'Year', 'time']], index=[0], columns=concept_dis_df.columns))

In [44]:
concept_dis_df

              concept                 name           type
0            iso_code             ISO Code         string
1         countryname          CountryName         string
2  uncertainty_bounds  Uncertainty bounds*         string
0             country              Country  entity_domain
0                year                 Year           time

In [50]:
concept_dis_df.to_csv('output/ddf--concepts--discrete.csv', index=False)

# Entities

In [96]:
entities = data[['ISO Code', 'CountryName']].copy()

In [97]:
entities['country'] = entities['ISO Code'].apply(to_concept_id)

In [98]:
entities.columns = ['iso_code', 'countryname', 'country']

In [100]:
entities = entities[['country', 'iso_code', 'countryname']]

In [101]:
entities = entities.drop_duplicates()

In [102]:
entities.to_csv('./output/ddf--entities--country.csv', index=False)

In [103]:
entities.head()

   country iso_code           countryname
0      afg      AFG           Afghanistan
3      ago      AGO                Angola
6      alb      ALB               Albania
9      and      AND               Andorra
12     are      ARE  United Arab Emirates

# data points

In [76]:
from functools import partial

In [78]:
k = 'stest'
k.startswith?

In [ ]:
'tet'.startswith

In [119]:
col = {}

for i in range(len(res)):

    col[res[i]]  = list(filter(lambda x: x.startswith(res[i]), data.columns))

In [120]:
col.keys()

dict_keys(['IMR', 'NMR', 'Infant.Deaths', 'Neonatal.Deaths', 'Under.five.Deaths', 'U5MR'])

In [121]:
col

{'IMR': ['IMR.1950',
  'IMR.1951',
  'IMR.1952',
  'IMR.1953',
  'IMR.1954',
  'IMR.1955',
  'IMR.1956',
  'IMR.1957',
  'IMR.1958',
  'IMR.1959',
  'IMR.1960',
  'IMR.1961',
  'IMR.1962',
  'IMR.1963',
  'IMR.1964',
  'IMR.1965',
  'IMR.1966',
  'IMR.1967',
  'IMR.1968',
  'IMR.1969',
  'IMR.1970',
  'IMR.1971',
  'IMR.1972',
  'IMR.1973',
  'IMR.1974',
  'IMR.1975',
  'IMR.1976',
  'IMR.1977',
  'IMR.1978',
  'IMR.1979',
  'IMR.1980',
  'IMR.1981',
  'IMR.1982',
  'IMR.1983',
  'IMR.1984',
  'IMR.1985',
  'IMR.1986',
  'IMR.1987',
  'IMR.1988',
  'IMR.1989',
  'IMR.1990',
  'IMR.1991',
  'IMR.1992',
  'IMR.1993',
  'IMR.1994',
  'IMR.1995',
  'IMR.1996',
  'IMR.1997',
  'IMR.1998',
  'IMR.1999',
  'IMR.2000',
  'IMR.2001',
  'IMR.2002',
  'IMR.2003',
  'IMR.2004',
  'IMR.2005',
  'IMR.2006',
  'IMR.2007',
  'IMR.2008',
  'IMR.2009',
  'IMR.2010',
  'IMR.2011',
  'IMR.2012',
  'IMR.2013',
  'IMR.2014',
  'IMR.2015'],
 'Infant.Deaths': ['Infant.Deaths.1950',
  'Infant.Deaths.1951',
  'Infant.Deaths.1952',
  'Infant.Deaths.1953',
  'Infant.Deaths.1954',
  'Infant.Deaths.1955',
  'Infant.Deaths.1956',
  'Infant.Deaths.1957',
  'Infant.Deaths.1958',
  'Infant.Deaths.1959',
  'Infant.Deaths.1960',
  'Infant.Deaths.1961',
  'Infant.Deaths.1962',
  'Infant.Deaths.1963',
  'Infant.Deaths.1964',
  'Infant.Deaths.1965',
  'Infant.Deaths.1966',
  'Infant.Deaths.1967',
  'Infant.Deaths.1968',
  'Infant.Deaths.1969',
  'Infant.Deaths.1970',
  'Infant.Deaths.1971',
  'Infant.Deaths.1972',
  'Infant.Deaths.1973',
  'Infant.Deaths.1974',
  'Infant.Deaths.1975',
  'Infant.Deaths.1976',
  'Infant.Deaths.1977',
  'Infant.Deaths.1978',
  'Infant.Deaths.1979',
  'Infant.Deaths.1980',
  'Infant.Deaths.1981',
  'Infant.Deaths.1982',
  'Infant.Deaths.1983',
  'Infant.Deaths.1984',
  'Infant.Deaths.1985',
  'Infant.Deaths.1986',
  'Infant.Deaths.1987',
  'Infant.Deaths.1988',
  'Infant.Deaths.1989',
  'Infant.Deaths.1990',
  'Infant.Deaths.1991',
  'Infant.Deaths.1992',
  'Infant.Deaths.1993',
  'Infant.Deaths.1994',
  'Infant.Deaths.1995',
  'Infant.Deaths.1996',
  'Infant.Deaths.1997',
  'Infant.Deaths.1998',
  'Infant.Deaths.1999',
  'Infant.Deaths.2000',
  'Infant.Deaths.2001',
  'Infant.Deaths.2002',
  'Infant.Deaths.2003',
  'Infant.Deaths.2004',
  'Infant.Deaths.2005',
  'Infant.Deaths.2006',
  'Infant.Deaths.2007',
  'Infant.Deaths.2008',
  'Infant.Deaths.2009',
  'Infant.Deaths.2010',
  'Infant.Deaths.2011',
  'Infant.Deaths.2012',
  'Infant.Deaths.2013',
  'Infant.Deaths.2014',
  'Infant.Deaths.2015'],
 'NMR': ['NMR.1950',
  'NMR.1951',
  'NMR.1952',
  'NMR.1953',
  'NMR.1954',
  'NMR.1955',
  'NMR.1956',
  'NMR.1957',
  'NMR.1958',
  'NMR.1959',
  'NMR.1960',
  'NMR.1961',
  'NMR.1962',
  'NMR.1963',
  'NMR.1964',
  'NMR.1965',
  'NMR.1966',
  'NMR.1967',
  'NMR.1968',
  'NMR.1969',
  'NMR.1970',
  'NMR.1971',
  'NMR.1972',
  'NMR.1973',
  'NMR.1974',
  'NMR.1975',
  'NMR.1976',
  'NMR.1977',
  'NMR.1978',
  'NMR.1979',
  'NMR.1980',
  'NMR.1981',
  'NMR.1982',
  'NMR.1983',
  'NMR.1984',
  'NMR.1985',
  'NMR.1986',
  'NMR.1987',
  'NMR.1988',
  'NMR.1989',
  'NMR.1990',
  'NMR.1991',
  'NMR.1992',
  'NMR.1993',
  'NMR.1994',
  'NMR.1995',
  'NMR.1996',
  'NMR.1997',
  'NMR.1998',
  'NMR.1999',
  'NMR.2000',
  'NMR.2001',
  'NMR.2002',
  'NMR.2003',
  'NMR.2004',
  'NMR.2005',
  'NMR.2006',
  'NMR.2007',
  'NMR.2008',
  'NMR.2009',
  'NMR.2010',
  'NMR.2011',
  'NMR.2012',
  'NMR.2013',
  'NMR.2014',
  'NMR.2015'],
 'Neonatal.Deaths': ['Neonatal.Deaths.1950',
  'Neonatal.Deaths.1951',
  'Neonatal.Deaths.1952',
  'Neonatal.Deaths.1953',
  'Neonatal.Deaths.1954',
  'Neonatal.Deaths.1955',
  'Neonatal.Deaths.1956',
  'Neonatal.Deaths.1957',
  'Neonatal.Deaths.1958',
  'Neonatal.Deaths.1959',
  'Neonatal.Deaths.1960',
  'Neonatal.Deaths.1961',
  'Neonatal.Deaths.1962',
  'Neonatal.Deaths.1963',
  'Neonatal.Deaths.1964',
  'Neonatal.Deaths.1965',
  'Neonatal.Deaths.1966',
  'Neonatal.Deaths.1967',
  'Neonatal.Deaths.1968',
  'Neonatal.Deaths.1969',
  'Neonatal.Deaths.1970',
  'Neonatal.Deaths.1971',
  'Neonatal.Deaths.1972',
  'Neonatal.Deaths.1973',
  'Neonatal.Deaths.1974',
  'Neonatal.Deaths.1975',
  'Neonatal.Deaths.1976',
  'Neonatal.Deaths.1977',
  'Neonatal.Deaths.1978',
  'Neonatal.Deaths.1979',
  'Neonatal.Deaths.1980',
  'Neonatal.Deaths.1981',
  'Neonatal.Deaths.1982',
  'Neonatal.Deaths.1983',
  'Neonatal.Deaths.1984',
  'Neonatal.Deaths.1985',
  'Neonatal.Deaths.1986',
  'Neonatal.Deaths.1987',
  'Neonatal.Deaths.1988',
  'Neonatal.Deaths.1989',
  'Neonatal.Deaths.1990',
  'Neonatal.Deaths.1991',
  'Neonatal.Deaths.1992',
  'Neonatal.Deaths.1993',
  'Neonatal.Deaths.1994',
  'Neonatal.Deaths.1995',
  'Neonatal.Deaths.1996',
  'Neonatal.Deaths.1997',
  'Neonatal.Deaths.1998',
  'Neonatal.Deaths.1999',
  'Neonatal.Deaths.2000',
  'Neonatal.Deaths.2001',
  'Neonatal.Deaths.2002',
  'Neonatal.Deaths.2003',
  'Neonatal.Deaths.2004',
  'Neonatal.Deaths.2005',
  'Neonatal.Deaths.2006',
  'Neonatal.Deaths.2007',
  'Neonatal.Deaths.2008',
  'Neonatal.Deaths.2009',
  'Neonatal.Deaths.2010',
  'Neonatal.Deaths.2011',
  'Neonatal.Deaths.2012',
  'Neonatal.Deaths.2013',
  'Neonatal.Deaths.2014',
  'Neonatal.Deaths.2015'],
 'U5MR': ['U5MR.1950',
  'U5MR.1951',
  'U5MR.1952',
  'U5MR.1953',
  'U5MR.1954',
  'U5MR.1955',
  'U5MR.1956',
  'U5MR.1957',
  'U5MR.1958',
  'U5MR.1959',
  'U5MR.1960',
  'U5MR.1961',
  'U5MR.1962',
  'U5MR.1963',
  'U5MR.1964',
  'U5MR.1965',
  'U5MR.1966',
  'U5MR.1967',
  'U5MR.1968',
  'U5MR.1969',
  'U5MR.1970',
  'U5MR.1971',
  'U5MR.1972',
  'U5MR.1973',
  'U5MR.1974',
  'U5MR.1975',
  'U5MR.1976',
  'U5MR.1977',
  'U5MR.1978',
  'U5MR.1979',
  'U5MR.1980',
  'U5MR.1981',
  'U5MR.1982',
  'U5MR.1983',
  'U5MR.1984',
  'U5MR.1985',
  'U5MR.1986',
  'U5MR.1987',
  'U5MR.1988',
  'U5MR.1989',
  'U5MR.1990',
  'U5MR.1991',
  'U5MR.1992',
  'U5MR.1993',
  'U5MR.1994',
  'U5MR.1995',
  'U5MR.1996',
  'U5MR.1997',
  'U5MR.1998',
  'U5MR.1999',
  'U5MR.2000',
  'U5MR.2001',
  'U5MR.2002',
  'U5MR.2003',
  'U5MR.2004',
  'U5MR.2005',
  'U5MR.2006',
  'U5MR.2007',
  'U5MR.2008',
  'U5MR.2009',
  'U5MR.2010',
  'U5MR.2011',
  'U5MR.2012',
  'U5MR.2013',
  'U5MR.2014',
  'U5MR.2015'],
 'Under.five.Deaths': ['Under.five.Deaths.1950',
  'Under.five.Deaths.1951',
  'Under.five.Deaths.1952',
  'Under.five.Deaths.1953',
  'Under.five.Deaths.1954',
  'Under.five.Deaths.1955',
  'Under.five.Deaths.1956',
  'Under.five.Deaths.1957',
  'Under.five.Deaths.1958',
  'Under.five.Deaths.1959',
  'Under.five.Deaths.1960',
  'Under.five.Deaths.1961',
  'Under.five.Deaths.1962',
  'Under.five.Deaths.1963',
  'Under.five.Deaths.1964',
  'Under.five.Deaths.1965',
  'Under.five.Deaths.1966',
  'Under.five.Deaths.1967',
  'Under.five.Deaths.1968',
  'Under.five.Deaths.1969',
  'Under.five.Deaths.1970',
  'Under.five.Deaths.1971',
  'Under.five.Deaths.1972',
  'Under.five.Deaths.1973',
  'Under.five.Deaths.1974',
  'Under.five.Deaths.1975',
  'Under.five.Deaths.1976',
  'Under.five.Deaths.1977',
  'Under.five.Deaths.1978',
  'Under.five.Deaths.1979',
  'Under.five.Deaths.1980',
  'Under.five.Deaths.1981',
  'Under.five.Deaths.1982',
  'Under.five.Deaths.1983',
  'Under.five.Deaths.1984',
  'Under.five.Deaths.1985',
  'Under.five.Deaths.1986',
  'Under.five.Deaths.1987',
  'Under.five.Deaths.1988',
  'Under.five.Deaths.1989',
  'Under.five.Deaths.1990',
  'Under.five.Deaths.1991',
  'Under.five.Deaths.1992',
  'Under.five.Deaths.1993',
  'Under.five.Deaths.1994',
  'Under.five.Deaths.1995',
  'Under.five.Deaths.1996',
  'Under.five.Deaths.1997',
  'Under.five.Deaths.1998',
  'Under.five.Deaths.1999',
  'Under.five.Deaths.2000',
  'Under.five.Deaths.2001',
  'Under.five.Deaths.2002',
  'Under.five.Deaths.2003',
  'Under.five.Deaths.2004',
  'Under.five.Deaths.2005',
  'Under.five.Deaths.2006',
  'Under.five.Deaths.2007',
  'Under.five.Deaths.2008',
  'Under.five.Deaths.2009',
  'Under.five.Deaths.2010',
  'Under.five.Deaths.2011',
  'Under.five.Deaths.2012',
  'Under.five.Deaths.2013',
  'Under.five.Deaths.2014',
  'Under.five.Deaths.2015']}

In [91]:
col1 = np.r_[data.columns[:3], col['IMR']]

In [92]:
new_col = list(map(lambda x: x[-4:], col['IMR']))

In [93]:
new_col = np.r_[data.columns[:3], new_col]

In [94]:
k = data[col1].copy()
k.columns = new_col

In [95]:
k

,ISO Code,CountryName,Uncertainty bounds*,1950,1951,1952,1953,1954,1955,1956,...,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015
0,AFG,Afghanistan,Lower,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,105.6,102.2,98.9,95.4,92.0,88.1,83.8,79.1,74.5,69.6
1,AFG,Afghanistan,Median,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,116.3,113.2,110.4,107.6,105.0,102.3,99.5,96.7,93.9,91.1
2,AFG,Afghanistan,Upper,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,129.6,126.7,124.2,122.2,120.6,119.3,118.5,118.2,118.3,118.8
3,AGO,Angola,Lower,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,159.9,153.2,145.7,137.8,130.1,122.1,114.9,107.7,101.1,94.8
4,AGO,Angola,Median,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,200.5,196.4,192.0,187.3,182.5,177.3,172.2,167.1,162.2,156.9
5,AGO,Angola,Upper,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,245.2,245.6,245.8,246.8,248.3,249.5,250.8,252.2,253.6,253.7
6,ALB,Albania,Lower,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,14.7,13.6,12.6,11.7,11.0,10.2,9.6,8.9,8.4,7.9
7,ALB,Albania,Median,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,19.5,18.7,17.9,17.3,16.6,16.0,15.5,14.9,14.4,14.0
8,ALB,Albania,Upper,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,26.0,25.8,25.5,25.4,25.2,25.1,25.0,24.9,24.9,24.9
9,AND,Andorra,Lower,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.9,2.8,2.6,2.5,2.3,2.2,2.1,2.0,1.9,1.8
10,AND,Andorra,Median,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3.7,3.6,3.5,3.4,3.3,3.2,3.1,3.0,2.9,2.8
11,AND,Andorra,Upper,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,4.8,4.8,4.8,4.8,4.8,4.8,4.8,4.7,4.8,4.7
12,ARE,United Arab Emirates,Lower,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,9.3,9.1,8.8,8.6,8.3,7.9,7.5,7.0,6.5,6.0
13,ARE,United Arab Emirates,Median,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,9.6,9.4,9.1,8.8,8.5,8.2,7.8,7.4,7.1,6.8
14,ARE,United Arab Emirates,Upper,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,9.9,9.7,9.4,9.1,8.7,8.4,8.1,7.9,7.8,7.7
15,ARG,Argentina,Lower,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,16.1,15.5,15.1,14.7,14.3,13.9,13.3,12.7,11.9,11.1
16,ARG,Argentina,Median,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,16.4,15.8,15.4,15.0,14.6,14.2,13.8,13.3,12.9,12.5
17,ARG,Argentina,Upper,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,16.7,16.1,15.7,15.3,14.9,14.5,14.2,14.0,13.9,14.0
18,ARM,Armenia,Lower,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,19.3,18.3,17.2,16.2,15.2,14.3,13.3,12.4,11.6,10.8
19,ARM,Armenia,Median,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,22.2,21.1,20.0,19.0,18.0,17.2,16.3,15.5,14.7,14.1
20,ARM,Armenia,Upper,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,25.0,24.0,23.0,22.2,21.3,20.6,19.9,19.4,18.8,18.3
21,ATG,Antigua & Barbuda,Lower,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,10.4,9.9,9.3,8.7,8.1,7.5,6.9,6.4,5.9,5.5
22,ATG,Antigua & Barbuda,Median,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,11.8,11.3,10.9,10.4,9.9,9.5,9.1,8.7,8.4,8.1
23,ATG,Antigua & Barbuda,Upper,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,13.4,13.0,12.7,12.4,12.3,12.2,12.1,12.0,12.0,11.9
24,AUS,Australia,Lower,30.6,30.3,29.7,28.9,28.2,27.4,26.8,...,5.5,5.3,5.1,4.9,4.7,4.5,4.2,4.0,3.7,3.5
25,AUS,Australia,Median,31.6,31.0,30.3,29.5,28.7,28.0,27.3,...,5.6,5.4,5.2,5.0,4.8,4.5,4.3,4.1,3.9,3.8
26,AUS,Australia,Upper,32.7,31.7,30.9,30.1,29.3,28.5,27.8,...,5.7,5.5,5.3,5.1,4.9,4.6,4.4,4.3,4.1,4.1
27,AUT,Austria,Lower,NaN,NaN,NaN,NaN,51.6,51.6,50.6,...,4.6,4.5,4.4,4.3,4.2,4.1,3.9,3.7,3.4,3.2
28,AUT,Austria,Median,NaN,NaN,NaN,NaN,55.0,53.4,51.7,...,4.8,4.7,4.6,4.5,4.4,4.2,4.0,3.9,3.7,3.5
29,AUT,Austria,Upper,NaN,NaN,NaN,NaN,58.5,55.2,53.0,...,4.9,4.8,4.7,4.6,4.5,4.4,4.2,4.1,4.0,3.9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
555,UZB,Uzbekistan,Lower,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,34.7,32.2,29.9,28.1,26.2,24.6,23.1,21.7,20.5,19.2
556,UZB,Uzbekistan,Median,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,52.5,50.8,49.2,47.6,46.1,44.6,43.2,41.8,40.4,39.1
557,UZB,Uzbekistan,Upper,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,76.1,76.5,77.2,77.6,78.1,78.7,78.8,78.9,79.2,79.5
558,VCT,St Vincent & the Grenadines,Lower,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,20.0,19.9,19.7,19.4,18.8,18.2,17.4,16.5,15.6,14.7
559,VCT,St Vincent & the Grenadines,Median,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,21.7,21.6,21.4,21.1,20.8,20.3,19.8,19.3,18.8,18.3
560,VCT,St Vincent & the Grenadines,Upper,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,23.6,23.4,23.3,23.1,22.9,22.8,22.7,22.7,22.8,22.9
561,VEN,Venezuela,Lower,NaN,83.0,82.8,82.1,81.4,80.4,79.2,...,17.6,17.1,16.7,16.3,15.8,15.2,14.4,13.5,12.6,11.7
562,VEN,Venezuela,Median,NaN,121.3,115.5,110.1,105.0,100.2,95.8,...,17.9,17.4,17.1,16.8,16.6,16.4,16.1,15.7,15.3,14.9
563,VEN,Venezuela,Upper,NaN,179.1,162.5,149.0,136.7,126.0,117.0,...,18.3,17.8,17.4,17.4,17.5,17.7,18.0,18.4,18.8,19.1
564,VNM,Vietnam,Lower,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,26.2,25.6,25.0,24.5,24.0,23.5,23.0,22.4,21.7,20.8
565,VNM,Vietnam,Median,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,27.7,26.9,26.2,25.5,24.8,24.2,23.5,22.9,22.3,21.7
566,VNM,Vietnam,Upper,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,29.5,28.5,27.6,26.6,25.7,24.9,24.1,23.4,23.0,22.7
567,VUT,Vanuatu,Lower,NaN,NaN,139.8,143.1,145.6,146.6,146.2,...,23.3,23.2,23.0,22.7,22.4,21.8,21.2,20.4,19.5,18.6
568,VUT,Vanuatu,Median,NaN,NaN,182.6,179.4,175.9,172.4,169.0,...,28.0,28.2,28.2,28.4,28.5,28.6,28.6,28.4,28.1,27.5
569,VUT,Vanuatu,Upper,NaN,NaN,238.5,224.9,214.3,205.0,197.7,...,33.7,34.2,34.8,35.6,36.6,37.7,38.8,39.5,40.0,40.5
570,WSM,Samoa,Lower,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,15.9,15.6,15.3,19.4,14.8,14.4,13.9,13.4,12.9,12.2
571,WSM,Samoa,Median,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,19.1,18.9,18.8,24.1,18.7,18.6,18.5,18.2,17.9,17.5
572,WSM,Samoa,Upper,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,22.6,22.6,22.4,28.8,22.4,22.6,22.9,23.3,23.5,23.7
573,YEM,Yemen,Lower,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,61.9,58.1,54.4,50.7,47.2,43.7,40.5,37.5,34.9,32.3
574,YEM,Yemen,Median,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,68.5,64.7,61.0,57.6,54.2,51.1,48.4,46.0,43.8,41.9
575,YEM,Yemen,Upper,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,75.5,71.9,68.5,65.3,62.5,60.1,58.0,56.3,55.1,54.3
576,ZAF,South Africa,Lower,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,62.5,60.7,58.0,53.5,45.1,41.3,38.9,34.5,32.1,30.5
577,ZAF,South Africa,Median,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,73.1,71.3,68.4,63.5,53.8,49.8,47.7,43.4,41.4,40.5
578,ZAF,South Africa,Upper,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,85.0,83.0,79.6,74.3,63.5,59.7,58.2,54.1,53.1,53.3
579,ZMB,Zambia,Lower,NaN,NaN,NaN,180.0,186.2,189.6,190.8,...,96.1,90.2,85.5,80.0,74.6,70.6,65.4,59.4,54.1,49.4
580,ZMB,Zambia,Median,NaN,NaN,NaN,238.0,233.3,229.3,224.6,...,104.5,98.0,93.1,87.4,82.1,78.6,74.4,70.2,66.6,64.0
581,ZMB,Zambia,Upper,NaN,NaN,NaN,314.0,293.6,277.9,265.6,...,113.0,106.0,101.2,95.7,90.4,87.6,84.8,82.4,81.1,81.3
582,ZWE,Zimbabwe,Lower,NaN,NaN,NaN,135.7,138.9,140.4,141.1,...,91.0,89.0,86.2,83.1,79.0,73.8,65.2,59.1,54.6,50.9
583,ZWE,Zimbabwe,Median,NaN,NaN,NaN,181.8,177.2,172.6,168.0,...,100.0,98.0,95.4,92.9,89.5,85.6,78.5,74.5,72.3,70.7
584,ZWE,Zimbabwe,Upper,NaN,NaN,NaN,245.4,227.3,213.3,201.3,...,110.2,108.4,106.0,104.1,102.2,100.7,96.2,95.1,96.3,97.6

In [104]:
gs = k.groupby(by='Uncertainty bounds*')

In [111]:
m = k.ix[gs.groups['Lower']]

m = m.set_index('ISO Code')

In [114]:
m = m.T['1950':].unstack()

In [116]:
m = m.reset_index().dropna()

In [117]:
m

      ISO Code level_1      0
11         AFG    1961  306.9
12         AFG    1962  305.5
13         AFG    1963  303.1
14         AFG    1964    300
15         AFG    1965  295.3
16         AFG    1966  290.6
17         AFG    1967  285.7
18         AFG    1968  280.7
19         AFG    1969  275.9
20         AFG    1970  270.9
21         AFG    1971  265.8
22         AFG    1972  260.9
23         AFG    1973  256.1
24         AFG    1974  251.6
25         AFG    1975  246.6
26         AFG    1976    242
27         AFG    1977  237.2
28         AFG    1978  231.7
29         AFG    1979  226.6
30         AFG    1980  221.3
31         AFG    1981  215.3
32         AFG    1982  209.8
33         AFG    1983  204.1
34         AFG    1984  198.5
35         AFG    1985  192.7
36         AFG    1986  186.8
37         AFG    1987    181
38         AFG    1988    175
39         AFG    1989  169.2
40         AFG    1990  163.1
...        ...     ...    ...
12840      ZWE    1986   71.2
12841      ZWE    1987   68.9
12842      ZWE    1988   67.7
12843      ZWE    1989   67.9
12844      ZWE    1990   69.7
12845      ZWE    1991   72.5
12846      ZWE    1992   76.3
12847      ZWE    1993   80.4
12848      ZWE    1994   84.3
12849      ZWE    1995   88.1
12850      ZWE    1996   91.3
12851      ZWE    1997   93.7
12852      ZWE    1998   95.2
12853      ZWE    1999     96
12854      ZWE    2000   96.3
12855      ZWE    2001   95.7
12856      ZWE    2002   95.1
12857      ZWE    2003   94.2
12858      ZWE    2004   93.4
12859      ZWE    2005   92.5
12860      ZWE    2006     91
12861      ZWE    2007     89
12862      ZWE    2008   86.2
12863      ZWE    2009   83.1
12864      ZWE    2010     79
12865      ZWE    2011   73.8
12866      ZWE    2012   65.2
12867      ZWE    2013   59.1
12868      ZWE    2014   54.6
12869      ZWE    2015   50.9

[10244 rows x 3 columns]

In [134]:
def extract_datapoints_country_year(data):
    """extract datapoints for each concept by country and year"""

    # first, construct a dict that contains all metrics as key and a list of
    # columns related to a metric as value of a key.
    # we will later pass the dict to data.loc[: col[key]] to get all data
    # point for a metric.

    metrics = []
    for i in data.columns[3:]:
        s = i[:-5]
        if not s in metrics:
            metrics.append(s)

    col = {}
    for m in metrics:
        col[m] = list(filter(lambda x: x.startswith(m), data.columns))

    # now we loop through each metrics and create data frame.
    res = {}
    for m in metrics:
        col_metric = np.r_[data.columns[:3], col[m]]
        # change the column form metirc.year to year
        col_metric_new = list(map(lambda x: x[-4:], col[m]))
        col_metric_new = np.r_[data.columns[:3], col_metric_new]

        data_metric = data[col_metric].copy()
        data_metric.columns = col_metric_new

        gs = data_metric.groupby(by='Uncertainty bounds*').groups

        for p in ['Lower', 'Median', 'Upper']:
            name = to_concept_id(m+'.'+p)
            headers = ['iso', 'year', name]
            data_bound = data_metric.ix[gs[p]]
            data_bound = data_bound.set_index('ISO Code')
            data_bound = data_bound.T['1950':]   # the data from source start from 1950
            data_bound = data_bound.unstack().reset_index().dropna()

            data_bound.columns = headers

            res[name] = data_bound

    return res

In [135]:
res = extract_datapoints_country_year(data)

In [136]:
res['imr_lower']

       iso  year imr_lower
11     AFG  1961     205.5
12     AFG  1962     204.5
13     AFG  1963     202.8
14     AFG  1964     200.7
15     AFG  1965     197.4
16     AFG  1966     194.2
17     AFG  1967     190.9
18     AFG  1968     187.5
19     AFG  1969     184.2
20     AFG  1970     180.7
21     AFG  1971     177.3
22     AFG  1972       174
23     AFG  1973     170.8
24     AFG  1974     167.8
25     AFG  1975     164.4
26     AFG  1976     161.4
27     AFG  1977     158.2
28     AFG  1978     154.5
29     AFG  1979     151.1
30     AFG  1980     147.7
31     AFG  1981       144
32     AFG  1982     140.6
33     AFG  1983       137
34     AFG  1984     133.5
35     AFG  1985     129.8
36     AFG  1986     126.1
37     AFG  1987     122.5
38     AFG  1988     118.8
39     AFG  1989     115.3
40     AFG  1990     111.6
...    ...   ...       ...
12840  ZWE  1986      48.4
12841  ZWE  1987      47.2
12842  ZWE  1988      46.6
12843  ZWE  1989      46.8
12844  ZWE  1990      47.8
12845  ZWE  1991      49.2
12846  ZWE  1992        51
12847  ZWE  1993      52.9
12848  ZWE  1994      54.5
12849  ZWE  1995      56.3
12850  ZWE  1996      57.6
12851  ZWE  1997      58.5
12852  ZWE  1998      58.9
12853  ZWE  1999        59
12854  ZWE  2000      58.8
12855  ZWE  2001      58.3
12856  ZWE  2002      57.7
12857  ZWE  2003      57.1
12858  ZWE  2004      56.8
12859  ZWE  2005      56.4
12860  ZWE  2006      55.8
12861  ZWE  2007      55.3
12862  ZWE  2008      54.2
12863  ZWE  2009      52.7
12864  ZWE  2010      50.4
12865  ZWE  2011      47.9
12866  ZWE  2012      42.5
12867  ZWE  2013      40.4
12868  ZWE  2014      37.9
12869  ZWE  2015      35.8

[10244 rows x 3 columns]